version: "3"

networks:
  example_pgqf_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24

services:
  validator:
    build:
      context: ../../
      dockerfile: ./sdk/examples/Dockerfile
    environment:
      - RUST_LOG=info
    command: ./anoma-devnode
    networks:
      example_pgqf_net:
        ipv4_address: 172.20.1.2

  solver:
    build:
      context: ../../
      dockerfile: ./sdk/examples/Dockerfile
    environment:
      - RUST_LOG=info
    command: ./pgqf-solver --peer 172.20.1.2:44668
    networks:
      example_pgqf_net:
        ipv4_address: 172.20.1.3
    depends_on:
      validator:
        condition: service_started

  client:
    build:
      context: ../../
      dockerfile: ./sdk/examples/Dockerfile
    environment:
      - RUST_LOG=info
    command: ./pgqf-client --peer 172.20.1.3:44667
    networks:
      example_pgqf_net:
        ipv4_address: 172.20.1.4
    depends_on:
      solver:
        condition: service_started
