[workspace]
members = [
  "network",
  "primitives",
  "vm",
  "stdpred",
  "sdk/client",
  "sdk/predicates",
  "sdk/predicates/derive",
  "sdk/solver",
  "sdk/devnode",
]

[profile.release]
debug = true
lto = true
opt-level = 3
strip = true
codegen-units = 1
incremental = false
