[workspace]
members = [
  "network",
  "primitives",
  "solver",
  "validator",
  "vm",
  "stdpred",
  "sdk/predicates",
]
default-members = ["solver", "validator"]

[profile.release]
debug = true
lto = true