[package]
name = "anoma-vm"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

[dependencies]
anoma-primitives = { path = "../primitives", default-features = false }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
anyhow = "1"
