[package]
name = "anoma-vm"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

[lib]
doctest = false

[dependencies]
anoma-primitives = { path = "../primitives", default-features = false }

bincode = "1.3"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
anyhow = "1"
