[package]
name = "anoma-predicates-sdk-macros"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"
description = "Anoma Standard Predicate Library Macros"

[lib]
doctest = false
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
